Repository wecode-bootcamp-korea/17-2nd-Ourbnb-frontend, pull requests merged in 2021-03, with the labels that each got.

#4 [17기 강민지] 리뷰반영 리팩토링 완료
  package-lock.json
  package.json
  public/data/roomListdata.json
  src/Pages/DetailListpage/DetailList.js
  src/Pages/DetailListpage/Imgscrollbox.js
  src/Pages/DetailListpage/List.js
  src/Pages/DetailListpage/ListCard.js
  src/Pages/DetailListpage/TypelBox.js
  src/Pages/Main/Main.js
  src/Pages/Map/Map.js
  src/Pages/Map/Map.scss
  src/Routes.js
  src/componenets/Nav/Nav.js
  src/config.js
  src/index.js
Labels: Status: 리뷰 요청

#3 [17기 허혜성] 디테일 페이지 (컴포넌트 간 state 이동을 위한 긴급머지요청)
  .eslintrc
  package-lock.json
  package.json
  public/data/detail.json
  public/favicon.ico
  public/images/air-conditioner.png
  public/images/calendar.png
  public/images/clothes-hanger.png
  public/images/cutlery.png
  public/images/doorway.png
  public/images/hair-dryer.png
  public/images/heat.png
  public/images/home.png
  public/images/homemark.png
  public/images/laundry.png
  public/images/left.png
  public/images/marker.png
  public/images/minus.png
  public/images/plus.png
  public/images/redstar.png
  public/images/right.png
  public/images/star.png
  public/images/television.png
  public/images/wifi.png
  public/index.html
  src/Pages/DetailListpage/DetailList.js
  src/Pages/DetailListpage/List.js
  src/Pages/DetailListpage/ListCard.js
  src/Pages/Detailpage/Component/BookingCard.js
  src/Pages/Detailpage/Component/Dropdown.js
  src/Pages/Detailpage/Component/GradeList.js
  src/Pages/Detailpage/Component/Location.js
  src/Pages/Detailpage/Component/Picture.js
  src/Pages/Detailpage/Component/Postscript.js
  src/Pages/Detailpage/Component/Review.js
  src/Pages/Detailpage/Component/RoomDetail.js
  src/Pages/Detailpage/Component/SliderImg.js
  src/Pages/Detailpage/Component/Title.js
  src/Pages/Detailpage/Detailpage.js
  src/Pages/Map/Map.js
  src/Routes.js
  src/componenets/Footer/Footer.js
Labels: Status: Accepted

#5 [17기 강민지] listpage 데이터 통신 및 filter 통신 구현완료
  package-lock.json
  package.json
  public/data/roomListdata.json
  src/Pages/DetailListpage/DetailList.js
  src/Pages/DetailListpage/List.js
  src/Pages/DetailListpage/ListCard.js
  src/Pages/DetailListpage/PriceBox.js
  src/Pages/DetailListpage/TypelBox.js
  src/Pages/Detailpage/Component/BookingCard.js
  src/Pages/Detailpage/Detailpage.js
  src/Pages/Main/Main.js
  src/Pages/Map/Map.js
  src/Routes.js
  src/componenets/Nav/Nav.js
  src/config.js
  src/index.js
Labels: Status: 수정 요청

#7 [17기 김연주] 리팩토링완료, 긴급merge요청
  .eslintrc
  package-lock.json
  public/images/google.jpg
  public/images/kakao.jpg
  public/index.html
  src/Pages/Join/Join.js
  src/Pages/Join/JoinModal.js
  src/Pages/Join/join.scss
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Routes.js
  src/componenets/Nav/Nav.js
  src/componenets/Nav/conponents/NavModal.js
  src/componenets/Nav/conponents/NavModal.scss
  src/config.js
  src/index.js
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#6 [17기 김연주] 리팩토링완료, 긴급merge요청
  package-lock.json
  package.json
  public/images/여행.jpg
  src/Pages/Join/Join.js
  src/Pages/Payment/Payment.js
  src/Pages/Payment/Payment.scss
  src/Pages/Payment/components/PaymentList.js
  src/Pages/Payment/components/Reservation.js
  src/Routes.js
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#8 [17기 허혜성] 마이페이지 구현 완료 및 결제페이지 수정
  public/data/detail.json
  public/data/mypage.json
  src/Pages/DetailListpage/DetailList.js
  src/Pages/Detailpage/Component/BookingCard.js
  src/Pages/Detailpage/Component/GradeList.js
  src/Pages/Detailpage/Component/Location.js
  src/Pages/Detailpage/Component/Picture.js
  src/Pages/Detailpage/Component/Postscript.js
  src/Pages/Detailpage/Component/Review.js
  src/Pages/Detailpage/Component/RoomDetail.js
  src/Pages/Detailpage/Component/SliderImg.js
  src/Pages/Detailpage/Component/Title.js
  src/Pages/Detailpage/Detailpage.js
  src/Pages/Join/Join.js
  src/Pages/Mypage/Componet/Cancel.js
  src/Pages/Mypage/Componet/CancelList.js
  src/Pages/Mypage/Componet/Past.js
  src/Pages/Mypage/Componet/PastList.js
  src/Pages/Mypage/Componet/Upcomming.js
  src/Pages/Mypage/Componet/UpcommingList.js
  src/Pages/Mypage/Mypage.js
  src/Pages/Payment/Payment.js
  src/Pages/Payment/components/PaymentList.js
  src/Pages/Payment/components/Reservation.js
  src/Routes.js
  src/componenets/Nav/Nav.js
Labels: Status: 리뷰 요청

#9 [17기 김연주] 결제페이지 두번째브렌치 수정중
  public/index.html
  src/Pages/Detailpage/Component/BookingCard.js
  src/Pages/Detailpage/Detailpage.js
  src/Pages/Join/Join.js
  src/Pages/Mypage/Mypage.js
  src/Pages/Payment/Payment.js
  src/Pages/Payment/Payment.scss
  src/Pages/Payment/components/PaymentList.js
  src/componenets/Nav/Nav.js
  src/config.js
Labels: Status: Accepted

#10 [17기 김연주] 최종수정중
  public/index.html
  src/Pages/Join/Join.js
  src/Routes.js
  src/componenets/Nav/Nav.js
  src/config.js
Labels: Status: Accepted
